//AUTH ACTIONS
export const LOGIN_ACTION = 'LOGIN_ACTION'
export const REGISTRATION_ACTION = 'REGISTRATION_ACTION_ACTION'
export const LOGOUT_ACTION = 'LOGOUT_ACTION'
export const CHECK_AUTH_ACTION = 'CHECK_AUTH'

//ALERTS 
export const ERROR_ALERT_ACTION = 'ERROR_ALERT_ACTION';

export const API_URL = `http://localhost:7000/api`